### ISSUE TITLE
FuncMap模块

### ISSUE THREAD

**Issue by xserve98** [koangel/grapeNet#1]
FastCall是否可以考虑关联函数返回值？
`func vestAbc(s string, i int) string {}`

`str:=FastCall(1, "Call 1", 2000)
`

**Comment by koangel** [comment]
嗯 会考虑，但是反射对于返回值目前处理起来比较麻烦，建议你尝试callback方式
例如：
func vestAbc(s string, i int,cb func(v string))

FastCall(1, "Call 1", 2000,cb)

**Comment by koangel** [comment]
已增加带有返回值的funcMap，请查收！
