### ISSUE TITLE
发现一个奇怪的bug,设置TcpNet/echo_client的代码可复现，win7_64  go1.12.5

### ISSUE THREAD

**Issue by restxx** [koangel/grapeNet#13]
func main() {
	log.Printf("start echo clients...")
	connNet := tcp.NewEmptyTcp() // 空的TCP

	connNet.OnHandler = RecvEchoMsgC
	connNet.OnClose = OnClose
	// 连接建立
	for i := 0; i < 1; i++ { //这里为1的时候服务器不返回数据
		_, err := connNet.Dial("127.0.0.1:22222", nil)
		if err != nil {
			log.Fatal(err)
		}
	}

	for i := 0; i < 1; i++ {//前面为1时这里执行多少次都没用
		connNet.NetCM.Broadcast([]byte(fmt.Sprintf("this is echo msg:%v", i)))
	}

**Comment by koangel** [comment]
新版本 在试试
