### ISSUE TITLE
websock js客户端

### ISSUE THREAD

**Issue by xserve2018** [koangel/grapeNet#2]
作者您好： 请问Websocket网络库能否支持js客户端？ 有实例吗？

**Comment by koangel** [comment]
我是直接在web上测试的ws链接，目前该模块不算特别完善，我稍后有空会写web的一些例子，目前暂时没有，我司大部分项目是cocos或unity3d

**Comment by xserve2018** [comment]
谢谢，我这边已经测试可以了

**Comment by xserve2018** [comment]
https://html.spec.whatwg.org/multipage/web-sockets.html#network

**Comment by koangel** [comment]
好的
